### ISSUE TITLE
Problem executing binaries installed using nvm (Node Version Manager)

### ISSUE THREAD

**Issue by kriswill** [mini-containers/base#5] opened 2015-03-13 19:44 UTC
Hi, I'm trying to use `mini/base` to create a minimal-nvm container.  see this Dockerfile:
```sh
FROM mini/base

RUN apk-install \
      bash \
      tar \
      curl \
      git \
      c-ares \
      libgcc \
      libstdc++ \
      libuv

RUN rm /bin/sh && ln -s /bin/bash /bin/sh && \
    touch ~/.bashrc

ENV NODE_VERSION iojs

RUN NVM_VERSION="$(curl -s -L http://latest.nvm.sh -o /dev/null -D - | grep -Ei '^Location: .*tag/v[0-9.]+' | grep -oEi 'v[0-9.]+')" && \
    echo $NVM_VERSION && \
    curl https://raw.githubusercontent.com/creationix/nvm/$NVM_VERSION/install.sh | sh && \
    source ~/.nvm/nvm.sh && \
    nvm install $NODE_VERSION
```
when running:
```sh
→ docker run --rm -it mini-nvm bash

bash-4.3# nvm run iojs -p process.versions
Running io.js v1.5.1
bash: /root/.nvm/versions/io.js/v1.5.1/bin/iojs: No such file or directory

bash-4.3# ls -la /root/.nvm/versions/io.js/v1.5.1/bin/iojs
-rwxrwxr-x    1 500      500       16545561 Mar  9 18:14 /root/.nvm/versions/io.js/v1.5.1/bin/iojs
kriswill 12 hours ago  
```
Any advice is appreciated!

**Comment by luislavena** [comment] 2015-03-16 15:24
@kriswill have you tried the same using `gliderlabs/alpine:3.1` instead?

https://github.com/gliderlabs/docker-alpine

I've zero experience with node and nvm to comment about this or to determine the real issue of the failure, but testing to see if the problem is consistent will be a start.

You can also check how the node package is built for Alpine itself:

- http://forum.alpinelinux.org/apk/main/x86_64/nodejs
- http://git.alpinelinux.org/cgit/aports/tree/main/nodejs/APKBUILD

**Comment by kriswill** [comment] 2015-03-16 20:51
@luislavena thanks for your reply!  I did try it with `gliderlabs/alpine:3.1` and the result was the same:

```sh
bash-4.3# iojs --versoin
bash: /root/.nvm/versions/io.js/v1.5.1/bin/iojs: No such file or directory
```

I suppose the linux binary that nvm downloads from the iojs.org site is either incompatible with alpine linux, or there is some other configuration issue.  I could probably make a package for iojs, but I'd prefer to use nvm to version select, since that enables the greatest amount of flexibility configuring this particular software, and would lend itself to better to CI.  I'll keep trying... 

PS, any further analysis is appreciated. :)

**Comment by luislavena** [comment] 2015-03-16 22:05
@kriswill 

> I suppose the linux binary that nvm downloads from the iojs.org site is either incompatible with alpine linux

This is most likely. Any existing binary for Linux might not work since Alpine uses musl as libc instead of glibc like traditional distributions.

https://www.alpinelinux.org/about/

> I could probably make a package for iojs, but I'd prefer to use nvm to version select,

Actually will be better if you build packages for the different versions, so you have really small images that only contains that particular version of iojs/nodejs instead of *all* of them.

Not only on network and bandwidth savings but also on clarity (eg. setup a explicit dockerfile for `iojs:1.0` or something vs using environment variables or tricky bash/sh scripts).

The whole idea behind using Alpine Linux and mini/base is to achieve the smallest and function specific container as possible instead of a general purpose one.

**Comment by kriswill** [comment] 2015-03-17 19:51
Thanks @luislavena, nvm is kind of like a package manager for use in development, allowing one to dynamically select what version of node/io.js they want.  For instance, it's used by Travis CI to setup a test run.  It also has the ability to download the source for node and compile it.  I haven't check to see if it would be able to perform a source compile on Alpine, been busy with other things.

I will:
[ ] - see if nvm can compile node/io.js on Alpine
[ ] - if so, make an Alpine package for io.js 1.5.1
[ ] - create a mini-iojs Docker image

These tasks will get me to the right place.  Thanks for all your help!

**Comment by pikeas** [comment] 2015-03-24 08:10
I was on #alpine-linux on Freenode a bit ago, and they were kind enough to push a build of iojs v1.6.2 (latest) to the testing repo.

**Comment by luislavena** [comment] 2015-03-24 15:13
@pikeas thank you for the info.

@kriswill considering there is a `APKBUILD` for iojs under testing:

http://git.alpinelinux.org/cgit/aports/tree/testing/iojs/APKBUILD?id=c8a18b22ab119ae31ac78340023a8c8ac380c4bb

I'm going to close this out. You might want to look at [docker-alpine-abuild](https://github.com/andyshinn/docker-alpine-abuild) which will allow you to package any APKBUILD package using Docker.

Hope that helps.

**Closed by luislavena** 2015-03-24 15:13 UTC

**Comment by thedug** [comment] 2015-04-05 07:24
@kriswill Were you able to get this to work?

**Comment by kriswill** [comment] 2015-04-05 07:38
@thedug I have concluded that building a base file system with the iojs compiled binary and npm baked in is the best way to do this.  using nvm from Docker would require an interactive shell, which isn't a good choice when using a supervisor to keep a process running for docker.

**Comment by thedug** [comment] 2015-04-05 07:46
@kriswill How are you installing iojs on alpine?

**Comment by thedug** [comment] 2015-04-06 04:19
This is what I ended up with..


RUN apk-install libstdc++

ENV iojs_version 1.6.3
RUN apk-install -t build-deps wget ca-certificates gcc g++ python make && \
    wget -q https://iojs.org/dist/v${iojs_version}/iojs-v${iojs_version}.tar.gz && \
    tar -xzf iojs-v${iojs_version}.tar.gz && \
    cd iojs-v${iojs_version} && \
    python ./configure && \
    make && \
    make install && \
    rm -rf iojs-v${iojs_version}.tar.gz && \
    rm -rf iojs-v${iojs_version} && \
    apk del --purge build-deps

**Comment by pikeas** [comment] 2015-04-06 05:18
For prebuilt ioJS:

    RUN \
        apk add -U -X http://nl.alpinelinux.org/alpine/edge/main/ \
            git=2.3.5-r0 \
            libstdc++=4.9.2-r4 && \
        apk add -U -X http://nl.alpinelinux.org/alpine/edge/testing/ \
            iojs=1.6.2-r0 && \
        rm -rf /var/cache/apk/*

**Comment by thedug** [comment] 2015-04-06 05:29
@pikeas I saw that but I'm at the mercy of the package maintainers. With the above, I can compile any version I want to test with and tag the versions for fast swapping.

**Comment by luislavena** [comment] 2015-04-08 20:28
@thedug @pikeas @kriswill I think you might find this interesting:

- https://registry.hub.docker.com/u/mhart/alpine-node/
- https://github.com/mhart/alpine-node

Leaving those links here for others.

Cheers.

**Comment by mbland** [comment] 2016-02-21 22:28
FYI, a giveaway that it's a glibc issue when you get a "No such file or directory" error from a binary that clearly exists is to check its dynamic symbol resolution via `ldd`:

```sh
# Upon login, in which /etc/profile.d/nvm.sh gets sourced:
nvm/versions/node/v5.6.0/bin/npm: exec: line 2: nvm/versions/node/v5.6.0/bin/node: not found
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v5.6.0 --silent` to unset it.

$ ls -l nvm/versions/node/v5.6.0/bin/node
-rwxrwxr-x    1 500      500       25196326 Feb  9 16:15 nvm/versions/node/v5.6.0/bin/node

$ nvm/versions/node/v5.6.0/bin/node
bash: nvm/versions/node/v5.6.0/bin/node: No such file or directory

$ ldd nvm/versions/node/v5.6.0/bin/node 
        /lib64/ld-linux-x86-64.so.2 (0x55994b70b000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x55994b70b000)
        librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x55994b70b000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fce4c176000)
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x55994b70b000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fce4bf63000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x55994b70b000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x55994b70b000)
Error relocating node: __isinf: symbol not found
Error relocating node: __rawmemchr: symbol not found
Error relocating node: __isnan: symbol not found
Error relocating node: __strtod_internal: symbol not found
Error relocating node: backtrace: symbol not found
```

Just got that trying to use nvm to install node 5.6.0 on an alpine:3.3 Docker image.
